displayName: Bot Wrangler Traefik Plugin
type: middleware
iconPath: .assets/icon.png

import: github.com/holysoles/bot-wrangler-traefik-plugin

summary: A plugin to helps manage and enforce your robots.txt against bots

testData:
  LogLevel: "INFO"
  BotAction: "PASS"
